name:                task
version:             0.2.0.0
license:             AllRightsReserved
author:              Sean Parsons
build-type:          Simple

ghc-options:
  - -Wall
  - -Werror
  - -threaded
  - -optl-fuse-ld=gold
  - -fno-warn-orphans 

ld-options:
  - -fuse-ld=gold

dependencies:
  - aeson
  - aeson-casing
  - base
  - bytestring
  - data-default-class
  - directory
  - filepath
  - generic-lens
  - lens
  - optparse-applicative
  - table-layout
  - time
  - text
  - vector

tests:
  task-test:
    main: Main.hs
    source-dirs: 
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-hedgehog

executable:
  main: Main.hs
  source-dirs: src
